-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Gamelogic2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    btn0 : IN STD_LOGIC;
    btn1 : IN STD_LOGIC;
    btn2 : IN STD_LOGIC;
    btn3 : IN STD_LOGIC;
    reset_game_in : IN STD_LOGIC;
    reset_game_out : OUT STD_LOGIC;
    right_wins : OUT STD_LOGIC;
    end_game : OUT STD_LOGIC;
    end_game_ap_vld : OUT STD_LOGIC;
    center_line_out_V : OUT STD_LOGIC_VECTOR (11 downto 0);
    center_line_in_V : IN STD_LOGIC_VECTOR (11 downto 0);
    right_out : OUT STD_LOGIC;
    right_in : IN STD_LOGIC );
end;


architecture behav of Gamelogic2 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "Gamelogic2,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.510000,HLS_SYN_LAT=13,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=627,HLS_SYN_LUT=926,HLS_VERSION=2018_3}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (37 downto 0) := "00000000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (37 downto 0) := "00000000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (37 downto 0) := "00000000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (37 downto 0) := "00000001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (37 downto 0) := "00000010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (37 downto 0) := "00000100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (37 downto 0) := "00001000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (37 downto 0) := "00010000000000000000000000000000000000";
    constant ap_ST_fsm_state36 : STD_LOGIC_VECTOR (37 downto 0) := "00100000000000000000000000000000000000";
    constant ap_ST_fsm_state37 : STD_LOGIC_VECTOR (37 downto 0) := "01000000000000000000000000000000000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (37 downto 0) := "10000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv14_140 : STD_LOGIC_VECTOR (13 downto 0) := "00000101000000";
    constant ap_const_lv13_1FF6 : STD_LOGIC_VECTOR (12 downto 0) := "1111111110110";
    constant ap_const_lv13_A : STD_LOGIC_VECTOR (12 downto 0) := "0000000001010";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_64 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100100";
    constant ap_const_lv7_32 : STD_LOGIC_VECTOR (6 downto 0) := "0110010";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_27F : STD_LOGIC_VECTOR (11 downto 0) := "001001111111";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal btn_count : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal game_over : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal RandSeed : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    signal first_run : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal new_center_cast1_fu_242_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal brmerge1_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge1_reg_593 : STD_LOGIC_VECTOR (0 downto 0);
    signal btn_count_loc_fu_278_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal btn_count_loc_reg_599 : STD_LOGIC_VECTOR (31 downto 0);
    signal game_over_load_load_fu_286_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal game_over_load_reg_606 : STD_LOGIC_VECTOR (0 downto 0);
    signal new_center_8_fu_484_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal new_center_8_reg_610 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_1_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_616 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_i_i_fu_501_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_i_i_reg_620 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_phi_mux_btn_count_flag_2_phi_fu_163_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal btn_count_flag_2_reg_160 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state38 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state38 : signal is "none";
    signal ap_phi_mux_btn_count_new_2_phi_fu_175_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal btn_count_new_2_reg_172 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_new_center_9_phi_fu_187_p6 : STD_LOGIC_VECTOR (13 downto 0);
    signal new_center_9_reg_184 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_phi_mux_right_wins_write_ass_phi_fu_198_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_run_load_load_fu_535_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_fu_545_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_i_fu_550_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_end_game_write_assig_phi_fu_213_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_new_center_s_phi_fu_228_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_512_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reset_game_out_preg : STD_LOGIC := '0';
    signal tmp_fu_250_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_250_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_256_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_256_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_272_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal new_center_cast_fu_246_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal new_center_fu_290_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal new_center_1_fu_300_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_s_fu_310_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_s_fu_310_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_1_fu_322_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_1_fu_322_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sel_tmp_fu_334_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_334_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal new_center_1_cast_fu_296_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_1_cast_fu_330_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sel_tmp3_fu_348_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_fu_354_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_fu_360_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal new_center_2_cast_fu_306_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal new_center_2_fu_340_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal sel_tmp9_fu_374_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp9_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_386_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal new_center_3_fu_366_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal sel_tmp7_fu_400_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_400_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_cast_fu_318_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal new_center_4_fu_392_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal sel_tmp6_fu_420_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp10_fu_426_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp10_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal new_center_5_fu_412_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal sel_tmp25_demorgan_fu_440_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp25_demorgan_fu_440_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp25_demorgan_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp12_fu_452_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp11_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp12_fu_452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal new_center_6_fu_432_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal sel_tmp32_demorgan_fu_466_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp32_demorgan_fu_466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp14_fu_478_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp13_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp14_fu_478_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal new_center_7_fu_458_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_i_i_fu_501_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_512_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_512_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_518_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_3_fu_561_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_569_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_512_ap_start : STD_LOGIC;
    signal grp_fu_512_ap_done : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (37 downto 0);

    component Gamelogic2_urem_3bkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        start : IN STD_LOGIC;
        done : OUT STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    Gamelogic2_urem_3bkb_U1 : component Gamelogic2_urem_3bkb
    generic map (
        ID => 1,
        NUM_STAGE => 36,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        start => grp_fu_512_ap_start,
        done => grp_fu_512_ap_done,
        din0 => grp_fu_512_p0,
        din1 => grp_fu_512_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_512_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    reset_game_out_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                reset_game_out_preg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    reset_game_out_preg <= reset_game_in;
                end if; 
            end if;
        end if;
    end process;


    btn_count_flag_2_reg_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_1_fu_492_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                btn_count_flag_2_reg_160 <= brmerge1_reg_593;
            elsif (((tmp_1_reg_616 = ap_const_lv1_1) and (game_over_load_reg_606 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state38))) then 
                btn_count_flag_2_reg_160 <= ap_const_lv1_1;
            elsif (((game_over_load_load_fu_286_p1 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                btn_count_flag_2_reg_160 <= brmerge1_fu_262_p2;
            end if; 
        end if;
    end process;

    btn_count_new_2_reg_172_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_1_fu_492_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                btn_count_new_2_reg_172 <= btn_count_loc_reg_599;
            elsif (((tmp_1_reg_616 = ap_const_lv1_1) and (game_over_load_reg_606 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state38))) then 
                btn_count_new_2_reg_172 <= ap_const_lv32_0;
            elsif (((game_over_load_load_fu_286_p1 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                btn_count_new_2_reg_172 <= btn_count_loc_fu_278_p3;
            end if; 
        end if;
    end process;

    new_center_9_reg_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((tmp_1_reg_616 = ap_const_lv1_1) and (game_over_load_reg_606 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state38)) or ((tmp_1_fu_492_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
                new_center_9_reg_184 <= new_center_8_reg_610;
            elsif (((game_over_load_load_fu_286_p1 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                new_center_9_reg_184 <= new_center_cast1_fu_242_p1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_1_reg_616 = ap_const_lv1_1) and (game_over_load_reg_606 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state38))) then
                RandSeed <= grp_fu_512_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                brmerge1_reg_593 <= brmerge1_fu_262_p2;
                btn_count_loc_reg_599 <= btn_count_loc_fu_278_p3;
                game_over_load_reg_606 <= game_over;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_btn_count_flag_2_phi_fu_163_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state38))) then
                btn_count <= ap_phi_mux_btn_count_new_2_phi_fu_175_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((first_run_load_load_fu_535_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state38))) then
                first_run <= ap_const_lv1_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((tmp_1_i_fu_550_p2 = ap_const_lv1_1) and (tmp_i_fu_545_p2 = ap_const_lv1_0) and (first_run_load_load_fu_535_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state38)) or ((tmp_i_fu_545_p2 = ap_const_lv1_1) and (first_run_load_load_fu_535_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state38)))) then
                game_over <= ap_const_lv1_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((game_over_load_load_fu_286_p1 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                new_center_8_reg_610 <= new_center_8_fu_484_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                tmp_1_reg_616 <= tmp_1_fu_492_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_1_fu_492_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                tmp_i_i_reg_620 <= tmp_i_i_fu_501_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, game_over_load_load_fu_286_p1, tmp_1_fu_492_p2, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((game_over_load_load_fu_286_p1 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state38;
                elsif (((game_over_load_load_fu_286_p1 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((tmp_1_fu_492_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state38;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                ap_NS_fsm <= ap_ST_fsm_state36;
            when ap_ST_fsm_state36 => 
                ap_NS_fsm <= ap_ST_fsm_state37;
            when ap_ST_fsm_state37 => 
                ap_NS_fsm <= ap_ST_fsm_state38;
            when ap_ST_fsm_state38 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state38 <= ap_CS_fsm(37);

    ap_done_assign_proc : process(ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_btn_count_flag_2_phi_fu_163_p6_assign_proc : process(game_over_load_reg_606, tmp_1_reg_616, btn_count_flag_2_reg_160, ap_CS_fsm_state38)
    begin
        if (((tmp_1_reg_616 = ap_const_lv1_1) and (game_over_load_reg_606 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state38))) then 
            ap_phi_mux_btn_count_flag_2_phi_fu_163_p6 <= ap_const_lv1_1;
        else 
            ap_phi_mux_btn_count_flag_2_phi_fu_163_p6 <= btn_count_flag_2_reg_160;
        end if; 
    end process;


    ap_phi_mux_btn_count_new_2_phi_fu_175_p6_assign_proc : process(game_over_load_reg_606, tmp_1_reg_616, ap_CS_fsm_state38, btn_count_new_2_reg_172)
    begin
        if (((tmp_1_reg_616 = ap_const_lv1_1) and (game_over_load_reg_606 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state38))) then 
            ap_phi_mux_btn_count_new_2_phi_fu_175_p6 <= ap_const_lv32_0;
        else 
            ap_phi_mux_btn_count_new_2_phi_fu_175_p6 <= btn_count_new_2_reg_172;
        end if; 
    end process;


    ap_phi_mux_end_game_write_assig_phi_fu_213_p6_assign_proc : process(ap_CS_fsm_state38, first_run_load_load_fu_535_p1, tmp_i_fu_545_p2, tmp_1_i_fu_550_p2)
    begin
        if (((tmp_1_i_fu_550_p2 = ap_const_lv1_0) and (tmp_i_fu_545_p2 = ap_const_lv1_0) and (first_run_load_load_fu_535_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state38))) then 
            ap_phi_mux_end_game_write_assig_phi_fu_213_p6 <= ap_const_lv1_0;
        elsif ((((tmp_1_i_fu_550_p2 = ap_const_lv1_1) and (tmp_i_fu_545_p2 = ap_const_lv1_0) and (first_run_load_load_fu_535_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state38)) or ((tmp_i_fu_545_p2 = ap_const_lv1_1) and (first_run_load_load_fu_535_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state38)))) then 
            ap_phi_mux_end_game_write_assig_phi_fu_213_p6 <= ap_const_lv1_1;
        else 
            ap_phi_mux_end_game_write_assig_phi_fu_213_p6 <= "X";
        end if; 
    end process;


    ap_phi_mux_new_center_9_phi_fu_187_p6_assign_proc : process(game_over_load_reg_606, new_center_8_reg_610, tmp_1_reg_616, ap_CS_fsm_state38, new_center_9_reg_184)
    begin
        if (((tmp_1_reg_616 = ap_const_lv1_1) and (game_over_load_reg_606 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state38))) then 
            ap_phi_mux_new_center_9_phi_fu_187_p6 <= new_center_8_reg_610;
        else 
            ap_phi_mux_new_center_9_phi_fu_187_p6 <= new_center_9_reg_184;
        end if; 
    end process;


    ap_phi_mux_new_center_s_phi_fu_228_p4_assign_proc : process(ap_CS_fsm_state38, ap_phi_mux_new_center_9_phi_fu_187_p6, first_run_load_load_fu_535_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then
            if ((first_run_load_load_fu_535_p1 = ap_const_lv1_0)) then 
                ap_phi_mux_new_center_s_phi_fu_228_p4 <= ap_phi_mux_new_center_9_phi_fu_187_p6;
            elsif ((first_run_load_load_fu_535_p1 = ap_const_lv1_1)) then 
                ap_phi_mux_new_center_s_phi_fu_228_p4 <= ap_const_lv14_140;
            else 
                ap_phi_mux_new_center_s_phi_fu_228_p4 <= "XXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_new_center_s_phi_fu_228_p4 <= "XXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_right_wins_write_ass_phi_fu_198_p6_assign_proc : process(ap_CS_fsm_state38, first_run_load_load_fu_535_p1, tmp_i_fu_545_p2, tmp_1_i_fu_550_p2)
    begin
        if ((((tmp_1_i_fu_550_p2 = ap_const_lv1_0) and (tmp_i_fu_545_p2 = ap_const_lv1_0) and (first_run_load_load_fu_535_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state38)) or ((tmp_1_i_fu_550_p2 = ap_const_lv1_1) and (tmp_i_fu_545_p2 = ap_const_lv1_0) and (first_run_load_load_fu_535_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state38)))) then 
            ap_phi_mux_right_wins_write_ass_phi_fu_198_p6 <= ap_const_lv1_0;
        elsif (((tmp_i_fu_545_p2 = ap_const_lv1_1) and (first_run_load_load_fu_535_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state38))) then 
            ap_phi_mux_right_wins_write_ass_phi_fu_198_p6 <= ap_const_lv1_1;
        else 
            ap_phi_mux_right_wins_write_ass_phi_fu_198_p6 <= "X";
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    brmerge1_fu_262_p2 <= (tmp_fu_250_p2 or tmp1_fu_256_p2);
    btn_count_loc_fu_278_p3 <= 
        tmp_s_fu_272_p2 when (brmerge1_fu_262_p2(0) = '1') else 
        btn_count;
    center_line_out_V <= 
        ap_const_lv12_0 when (tmp_3_fu_561_p3(0) = '1') else 
        tmp_4_fu_569_p1;
    end_game <= ap_phi_mux_end_game_write_assig_phi_fu_213_p6(0);

    end_game_ap_vld_assign_proc : process(ap_CS_fsm_state38, first_run_load_load_fu_535_p1)
    begin
        if (((first_run_load_load_fu_535_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state38))) then 
            end_game_ap_vld <= ap_const_logic_1;
        else 
            end_game_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    first_run_load_load_fu_535_p1 <= first_run;
    game_over_load_load_fu_286_p1 <= game_over;

    grp_fu_512_ap_start_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_512_ap_start <= ap_const_logic_1;
        else 
            grp_fu_512_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_512_p0 <= std_logic_vector(unsigned(ap_const_lv32_64) + unsigned(tmp_i_i_reg_620));
    grp_fu_512_p1 <= ap_const_lv32_64(8 - 1 downto 0);
        new_center_1_cast_fu_296_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(new_center_fu_290_p2),14));

    new_center_1_fu_300_p2 <= std_logic_vector(unsigned(new_center_cast_fu_246_p1) + unsigned(ap_const_lv13_A));
    new_center_2_cast_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(new_center_1_fu_300_p2),14));
    new_center_2_fu_340_p3 <= 
        new_center_1_cast_fu_296_p1 when (sel_tmp_fu_334_p2(0) = '1') else 
        p_1_cast_fu_330_p1;
    new_center_3_fu_366_p3 <= 
        new_center_2_cast_fu_306_p1 when (sel_tmp5_fu_360_p2(0) = '1') else 
        new_center_2_fu_340_p3;
    new_center_4_fu_392_p3 <= 
        new_center_2_cast_fu_306_p1 when (sel_tmp2_fu_386_p2(0) = '1') else 
        new_center_3_fu_366_p3;
    new_center_5_fu_412_p3 <= 
        p_cast_fu_318_p1 when (sel_tmp8_fu_406_p2(0) = '1') else 
        new_center_4_fu_392_p3;
    new_center_6_fu_432_p3 <= 
        new_center_2_cast_fu_306_p1 when (sel_tmp10_fu_426_p2(0) = '1') else 
        new_center_5_fu_412_p3;
    new_center_7_fu_458_p3 <= 
        new_center_1_cast_fu_296_p1 when (sel_tmp12_fu_452_p2(0) = '1') else 
        new_center_6_fu_432_p3;
    new_center_8_fu_484_p3 <= 
        new_center_1_cast_fu_296_p1 when (sel_tmp14_fu_478_p2(0) = '1') else 
        new_center_7_fu_458_p3;
    new_center_cast1_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(center_line_in_V),14));
    new_center_cast_fu_246_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(center_line_in_V),13));
    new_center_fu_290_p2 <= std_logic_vector(unsigned(new_center_cast_fu_246_p1) + unsigned(ap_const_lv13_1FF6));
    p_1_cast_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_1_fu_322_p3),14));
    p_1_fu_322_p0 <= (0=>btn3, others=>'-');
    p_1_fu_322_p3 <= 
        new_center_1_fu_300_p2 when (p_1_fu_322_p0(0) = '1') else 
        new_center_cast_fu_246_p1;
        p_cast_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_s_fu_310_p3),14));

    p_s_fu_310_p0 <= (0=>btn3, others=>'-');
    p_s_fu_310_p3 <= 
        new_center_fu_290_p2 when (p_s_fu_310_p0(0) = '1') else 
        new_center_cast_fu_246_p1;

    reset_game_out_assign_proc : process(ap_start, ap_CS_fsm_state1, reset_game_in, reset_game_out_preg)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            reset_game_out <= reset_game_in;
        else 
            reset_game_out <= reset_game_out_preg;
        end if; 
    end process;

    right_out <= '1' when (unsigned(tmp_2_fu_518_p1) > unsigned(ap_const_lv7_32)) else '0';
    right_wins <= ap_phi_mux_right_wins_write_ass_phi_fu_198_p6(0);
    sel_tmp10_fu_426_p0 <= (0=>btn0, others=>'-');
    sel_tmp10_fu_426_p2 <= (sel_tmp6_fu_420_p2 and sel_tmp10_fu_426_p0);
    sel_tmp11_fu_446_p2 <= (sel_tmp25_demorgan_fu_440_p2 xor ap_const_lv1_1);
    sel_tmp12_fu_452_p0 <= (0=>btn2, others=>'-');
    sel_tmp12_fu_452_p2 <= (sel_tmp12_fu_452_p0 and sel_tmp11_fu_446_p2);
    sel_tmp13_fu_472_p2 <= (sel_tmp32_demorgan_fu_466_p2 xor ap_const_lv1_1);
    sel_tmp14_fu_478_p0 <= (0=>btn1, others=>'-');
    sel_tmp14_fu_478_p2 <= (sel_tmp14_fu_478_p0 and sel_tmp13_fu_472_p2);
    sel_tmp1_fu_380_p2 <= (sel_tmp9_fu_374_p2 and sel_tmp4_fu_354_p2);
    sel_tmp25_demorgan_fu_440_p0 <= (0=>right_in, others=>'-');
    sel_tmp25_demorgan_fu_440_p1 <= (0=>btn0, others=>'-');
    sel_tmp25_demorgan_fu_440_p2 <= (sel_tmp25_demorgan_fu_440_p1 or sel_tmp25_demorgan_fu_440_p0);
    sel_tmp2_fu_386_p1 <= (0=>btn1, others=>'-');
    sel_tmp2_fu_386_p2 <= (sel_tmp2_fu_386_p1 and sel_tmp1_fu_380_p2);
    sel_tmp32_demorgan_fu_466_p1 <= (0=>btn2, others=>'-');
    sel_tmp32_demorgan_fu_466_p2 <= (sel_tmp32_demorgan_fu_466_p1 or sel_tmp25_demorgan_fu_440_p2);
    sel_tmp3_fu_348_p0 <= (0=>btn0, others=>'-');
    sel_tmp3_fu_348_p2 <= (sel_tmp3_fu_348_p0 xor ap_const_lv1_1);
    sel_tmp4_fu_354_p0 <= (0=>right_in, others=>'-');
    sel_tmp4_fu_354_p2 <= (sel_tmp4_fu_354_p0 and sel_tmp3_fu_348_p2);
    sel_tmp5_fu_360_p1 <= (0=>btn2, others=>'-');
    sel_tmp5_fu_360_p2 <= (sel_tmp5_fu_360_p1 and sel_tmp4_fu_354_p2);
    sel_tmp6_fu_420_p0 <= (0=>right_in, others=>'-');
    sel_tmp6_fu_420_p2 <= (sel_tmp6_fu_420_p0 xor ap_const_lv1_1);
    sel_tmp7_fu_400_p0 <= (0=>btn1, others=>'-');
    sel_tmp7_fu_400_p2 <= (sel_tmp7_fu_400_p0 xor ap_const_lv1_1);
    sel_tmp8_fu_406_p2 <= (sel_tmp7_fu_400_p2 and sel_tmp1_fu_380_p2);
    sel_tmp9_fu_374_p0 <= (0=>btn2, others=>'-');
    sel_tmp9_fu_374_p2 <= (sel_tmp9_fu_374_p0 xor ap_const_lv1_1);
    sel_tmp_fu_334_p0 <= (0=>right_in, others=>'-');
    sel_tmp_fu_334_p1 <= (0=>btn0, others=>'-');
    sel_tmp_fu_334_p2 <= (sel_tmp_fu_334_p1 and sel_tmp_fu_334_p0);
    tmp1_fu_256_p0 <= (0=>btn0, others=>'-');
    tmp1_fu_256_p1 <= (0=>btn3, others=>'-');
    tmp1_fu_256_p2 <= (tmp1_fu_256_p1 or tmp1_fu_256_p0);
    tmp_1_fu_492_p2 <= "1" when (signed(btn_count_loc_reg_599) > signed(ap_const_lv32_A)) else "0";
    tmp_1_i_fu_550_p2 <= "1" when (unsigned(center_line_in_V) > unsigned(ap_const_lv12_27F)) else "0";
    tmp_2_fu_518_p1 <= grp_fu_512_p2(7 - 1 downto 0);
    tmp_3_fu_561_p3 <= ap_phi_mux_new_center_s_phi_fu_228_p4(13 downto 13);
    tmp_4_fu_569_p1 <= ap_phi_mux_new_center_s_phi_fu_228_p4(12 - 1 downto 0);
    tmp_fu_250_p0 <= (0=>btn1, others=>'-');
    tmp_fu_250_p1 <= (0=>btn2, others=>'-');
    tmp_fu_250_p2 <= (tmp_fu_250_p1 or tmp_fu_250_p0);
    tmp_i_fu_545_p2 <= "1" when (center_line_in_V = ap_const_lv12_0) else "0";
    tmp_i_i_fu_501_p1 <= RandSeed;
    tmp_i_i_fu_501_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv32_D) * signed(tmp_i_i_fu_501_p1))), 32));
    tmp_s_fu_272_p2 <= std_logic_vector(unsigned(btn_count) + unsigned(ap_const_lv32_1));
end behav;
