# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/PYNQ-Z1_C.xdc

# Block Designs: bd/Testing_HDMI/Testing_HDMI.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testing_HDMI || ORIG_REF_NAME==Testing_HDMI} -quiet] -quiet

# IP: bd/Testing_HDMI/ip/Testing_HDMI_HDMI_test_0_0/Testing_HDMI_HDMI_test_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testing_HDMI_HDMI_test_0_0 || ORIG_REF_NAME==Testing_HDMI_HDMI_test_0_0} -quiet] -quiet

# IP: bd/Testing_HDMI/ip/Testing_HDMI_clk_wiz_0_0/Testing_HDMI_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testing_HDMI_clk_wiz_0_0 || ORIG_REF_NAME==Testing_HDMI_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Testing_HDMI/ip/Testing_HDMI_clean_button_0_0/Testing_HDMI_clean_button_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testing_HDMI_clean_button_0_0 || ORIG_REF_NAME==Testing_HDMI_clean_button_0_0} -quiet] -quiet

# IP: bd/Testing_HDMI/ip/Testing_HDMI_clean_button_0_1/Testing_HDMI_clean_button_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testing_HDMI_clean_button_0_1 || ORIG_REF_NAME==Testing_HDMI_clean_button_0_1} -quiet] -quiet

# IP: bd/Testing_HDMI/ip/Testing_HDMI_clean_button_1_0/Testing_HDMI_clean_button_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testing_HDMI_clean_button_1_0 || ORIG_REF_NAME==Testing_HDMI_clean_button_1_0} -quiet] -quiet

# IP: bd/Testing_HDMI/ip/Testing_HDMI_clean_button_1_1/Testing_HDMI_clean_button_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testing_HDMI_clean_button_1_1 || ORIG_REF_NAME==Testing_HDMI_clean_button_1_1} -quiet] -quiet

# IP: bd/Testing_HDMI/ip/Testing_HDMI_Interface_0_1/Testing_HDMI_Interface_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testing_HDMI_Interface_0_1 || ORIG_REF_NAME==Testing_HDMI_Interface_0_1} -quiet] -quiet

# IP: bd/Testing_HDMI/ip/Testing_HDMI_Game_logic_0_0/Testing_HDMI_Game_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testing_HDMI_Game_logic_0_0 || ORIG_REF_NAME==Testing_HDMI_Game_logic_0_0} -quiet] -quiet

# XDC: bd/Testing_HDMI/Testing_HDMI_ooc.xdc
