// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Interface2_HH_
#define _Interface2_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct Interface2 : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<10> > x_V;
    sc_in< sc_lv<10> > y_V;
    sc_out< sc_lv<8> > XY_Red_V;
    sc_out< sc_lv<8> > XY_Green_V;
    sc_out< sc_lv<8> > XY_Blue_V;
    sc_in< sc_lv<10> > center_line_V;
    sc_in< sc_logic > right_r;


    // Module declarations
    Interface2(sc_module_name name);
    SC_HAS_PROCESS(Interface2);

    ~Interface2();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<5> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<1> > tmp_fu_103_p2;
    sc_signal< sc_lv<1> > tmp_reg_191;
    sc_signal< sc_lv<1> > brmerge247_i_fu_121_p2;
    sc_signal< sc_lv<1> > brmerge247_i_reg_198;
    sc_signal< sc_lv<1> > tmp_1_fu_127_p2;
    sc_signal< sc_lv<1> > tmp_1_reg_202;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > grp_fu_97_p2;
    sc_signal< sc_lv<1> > p_not248_i_reg_206;
    sc_signal< sc_lv<1> > brmerge250_i_fu_137_p2;
    sc_signal< sc_lv<1> > brmerge250_i_reg_211;
    sc_signal< sc_lv<1> > brmerge252_i_fu_143_p2;
    sc_signal< sc_lv<1> > brmerge252_i_reg_215;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > tmp_2_reg_219;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > or_cond_fu_156_p2;
    sc_signal< sc_lv<1> > or_cond_reg_223;
    sc_signal< sc_lv<1> > tmp_5_fu_162_p2;
    sc_signal< sc_lv<1> > tmp_5_reg_227;
    sc_signal< sc_lv<8> > XY_Red_V_preg;
    sc_signal< sc_lv<1> > brmerge_i_fu_109_p2;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<8> > XY_Blue_V_preg;
    sc_signal< sc_lv<8> > XY_Green_V_preg;
    sc_signal< sc_lv<1> > brmerge_i_fu_109_p1;
    sc_signal< sc_lv<1> > right_not_i_fu_115_p0;
    sc_signal< sc_lv<1> > right_not_i_fu_115_p2;
    sc_signal< sc_lv<1> > right_not249_i_fu_132_p0;
    sc_signal< sc_lv<1> > right_not249_i_fu_132_p2;
    sc_signal< sc_lv<1> > brmerge252_i_fu_143_p1;
    sc_signal< sc_lv<1> > tmp_3_fu_147_p2;
    sc_signal< sc_lv<1> > tmp_4_fu_151_p2;
    sc_signal< sc_lv<5> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<5> ap_ST_fsm_state1;
    static const sc_lv<5> ap_ST_fsm_state2;
    static const sc_lv<5> ap_ST_fsm_state3;
    static const sc_lv<5> ap_ST_fsm_state4;
    static const sc_lv<5> ap_ST_fsm_state5;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<10> ap_const_lv10_27;
    static const sc_lv<10> ap_const_lv10_140;
    static const sc_lv<10> ap_const_lv10_280;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_XY_Blue_V();
    void thread_XY_Green_V();
    void thread_XY_Red_V();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_brmerge247_i_fu_121_p2();
    void thread_brmerge250_i_fu_137_p2();
    void thread_brmerge252_i_fu_143_p1();
    void thread_brmerge252_i_fu_143_p2();
    void thread_brmerge_i_fu_109_p1();
    void thread_brmerge_i_fu_109_p2();
    void thread_grp_fu_97_p2();
    void thread_or_cond_fu_156_p2();
    void thread_right_not249_i_fu_132_p0();
    void thread_right_not249_i_fu_132_p2();
    void thread_right_not_i_fu_115_p0();
    void thread_right_not_i_fu_115_p2();
    void thread_tmp_1_fu_127_p2();
    void thread_tmp_3_fu_147_p2();
    void thread_tmp_4_fu_151_p2();
    void thread_tmp_5_fu_162_p2();
    void thread_tmp_fu_103_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
