// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Interface2_HH_
#define _Interface2_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct Interface2 : public sc_module {
    // Port declarations 11
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<10> > x_V;
    sc_in< sc_lv<10> > y_V;
    sc_out< sc_lv<8> > XY_Red_V;
    sc_out< sc_lv<8> > XY_Green_V;
    sc_out< sc_lv<8> > XY_Blue_V;
    sc_in< sc_lv<12> > center_line_V;
    sc_in< sc_logic > right_r;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    Interface2(sc_module_name name);
    SC_HAS_PROCESS(Interface2);

    ~Interface2();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<8> > storemerge5_cast_fu_120_p3;
    sc_signal< sc_lv<1> > tmp_fu_92_p2;
    sc_signal< sc_lv<1> > tmp_2_fu_98_p2;
    sc_signal< sc_lv<8> > storemerge6_fu_150_p3;
    sc_signal< sc_lv<1> > tmp_1_fu_138_p2;
    sc_signal< sc_lv<1> > tmp_3_fu_144_p2;
    sc_signal< sc_lv<8> > storemerge7_cast_fu_167_p3;
    sc_signal< sc_lv<8> > storemerge_fu_129_p3;
    sc_signal< sc_lv<12> > tmp_4_cast_fu_104_p1;
    sc_signal< sc_lv<1> > tmp_6_fu_108_p2;
    sc_signal< sc_lv<1> > not_tmp_6_fu_114_p2;
    sc_signal< sc_lv<1> > storemerge6_fu_150_p0;
    sc_signal< sc_lv<1> > not_right_fu_161_p0;
    sc_signal< sc_lv<1> > not_right_fu_161_p2;
    sc_signal< bool > ap_condition_39;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<10> ap_const_lv10_28;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<10> ap_const_lv10_140;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_XY_Blue_V();
    void thread_XY_Green_V();
    void thread_XY_Red_V();
    void thread_ap_condition_39();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_not_right_fu_161_p0();
    void thread_not_right_fu_161_p2();
    void thread_not_tmp_6_fu_114_p2();
    void thread_storemerge5_cast_fu_120_p3();
    void thread_storemerge6_fu_150_p0();
    void thread_storemerge6_fu_150_p3();
    void thread_storemerge7_cast_fu_167_p3();
    void thread_storemerge_fu_129_p3();
    void thread_tmp_1_fu_138_p2();
    void thread_tmp_2_fu_98_p2();
    void thread_tmp_3_fu_144_p2();
    void thread_tmp_4_cast_fu_104_p1();
    void thread_tmp_6_fu_108_p2();
    void thread_tmp_fu_92_p2();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
