// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Interface,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.763500,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=19,HLS_VERSION=2018_3}" *)

module Interface (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_V,
        y_V,
        XY_Red_V,
        XY_Green_V,
        XY_Blue_V
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [9:0] x_V;
input  [9:0] y_V;
output  [7:0] XY_Red_V;
output  [7:0] XY_Green_V;
output  [7:0] XY_Blue_V;

wire   [7:0] storemerge2_fu_69_p3;
wire   [0:0] tmp_fu_63_p2;
wire   [0:0] not_tmp_fu_79_p2;

assign XY_Blue_V = storemerge2_fu_69_p3;

assign XY_Green_V = storemerge2_fu_69_p3;

assign XY_Red_V = ((not_tmp_fu_79_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign not_tmp_fu_79_p2 = (tmp_fu_63_p2 ^ 1'd1);

assign storemerge2_fu_69_p3 = ((tmp_fu_63_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign tmp_fu_63_p2 = ((x_V > 10'd200) ? 1'b1 : 1'b0);

endmodule //Interface
