# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/itr9fc/Desktop/FPGA__Proj/HDMI_game_project/HDMI_game_project.srcs/sources_1/bd/Testing_HDMI/ip/Testing_HDMI_Gamelogic2_0_0/Testing_HDMI_Gamelogic2_0_0.xci
# IP: The module: 'Testing_HDMI_Gamelogic2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/itr9fc/Desktop/FPGA__Proj/HDMI_game_project/HDMI_game_project.srcs/sources_1/bd/Testing_HDMI/ip/Testing_HDMI_Gamelogic2_0_0/constraints/Gamelogic2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Testing_HDMI_Gamelogic2_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/itr9fc/Desktop/FPGA__Proj/HDMI_game_project/HDMI_game_project.srcs/sources_1/bd/Testing_HDMI/ip/Testing_HDMI_Gamelogic2_0_0/Testing_HDMI_Gamelogic2_0_0.xci
# IP: The module: 'Testing_HDMI_Gamelogic2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/itr9fc/Desktop/FPGA__Proj/HDMI_game_project/HDMI_game_project.srcs/sources_1/bd/Testing_HDMI/ip/Testing_HDMI_Gamelogic2_0_0/constraints/Gamelogic2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Testing_HDMI_Gamelogic2_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
