// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Game_logic,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.880875,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=2,HLS_SYN_FF=859,HLS_SYN_LUT=943,HLS_VERSION=2018_3}" *)

module Game_logic (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        rst,
        btn1,
        btn2,
        btn3,
        slow_clk,
        lose,
        time_remaining_out_V,
        time_remaining_in_V,
        verify1_out,
        verify2_out,
        verify3_out
);

parameter    ap_ST_fsm_state1 = 70'd1;
parameter    ap_ST_fsm_state2 = 70'd2;
parameter    ap_ST_fsm_state3 = 70'd4;
parameter    ap_ST_fsm_state4 = 70'd8;
parameter    ap_ST_fsm_state5 = 70'd16;
parameter    ap_ST_fsm_state6 = 70'd32;
parameter    ap_ST_fsm_state7 = 70'd64;
parameter    ap_ST_fsm_state8 = 70'd128;
parameter    ap_ST_fsm_state9 = 70'd256;
parameter    ap_ST_fsm_state10 = 70'd512;
parameter    ap_ST_fsm_state11 = 70'd1024;
parameter    ap_ST_fsm_state12 = 70'd2048;
parameter    ap_ST_fsm_state13 = 70'd4096;
parameter    ap_ST_fsm_state14 = 70'd8192;
parameter    ap_ST_fsm_state15 = 70'd16384;
parameter    ap_ST_fsm_state16 = 70'd32768;
parameter    ap_ST_fsm_state17 = 70'd65536;
parameter    ap_ST_fsm_state18 = 70'd131072;
parameter    ap_ST_fsm_state19 = 70'd262144;
parameter    ap_ST_fsm_state20 = 70'd524288;
parameter    ap_ST_fsm_state21 = 70'd1048576;
parameter    ap_ST_fsm_state22 = 70'd2097152;
parameter    ap_ST_fsm_state23 = 70'd4194304;
parameter    ap_ST_fsm_state24 = 70'd8388608;
parameter    ap_ST_fsm_state25 = 70'd16777216;
parameter    ap_ST_fsm_state26 = 70'd33554432;
parameter    ap_ST_fsm_state27 = 70'd67108864;
parameter    ap_ST_fsm_state28 = 70'd134217728;
parameter    ap_ST_fsm_state29 = 70'd268435456;
parameter    ap_ST_fsm_state30 = 70'd536870912;
parameter    ap_ST_fsm_state31 = 70'd1073741824;
parameter    ap_ST_fsm_state32 = 70'd2147483648;
parameter    ap_ST_fsm_state33 = 70'd4294967296;
parameter    ap_ST_fsm_state34 = 70'd8589934592;
parameter    ap_ST_fsm_state35 = 70'd17179869184;
parameter    ap_ST_fsm_state36 = 70'd34359738368;
parameter    ap_ST_fsm_state37 = 70'd68719476736;
parameter    ap_ST_fsm_state38 = 70'd137438953472;
parameter    ap_ST_fsm_state39 = 70'd274877906944;
parameter    ap_ST_fsm_state40 = 70'd549755813888;
parameter    ap_ST_fsm_state41 = 70'd1099511627776;
parameter    ap_ST_fsm_state42 = 70'd2199023255552;
parameter    ap_ST_fsm_state43 = 70'd4398046511104;
parameter    ap_ST_fsm_state44 = 70'd8796093022208;
parameter    ap_ST_fsm_state45 = 70'd17592186044416;
parameter    ap_ST_fsm_state46 = 70'd35184372088832;
parameter    ap_ST_fsm_state47 = 70'd70368744177664;
parameter    ap_ST_fsm_state48 = 70'd140737488355328;
parameter    ap_ST_fsm_state49 = 70'd281474976710656;
parameter    ap_ST_fsm_state50 = 70'd562949953421312;
parameter    ap_ST_fsm_state51 = 70'd1125899906842624;
parameter    ap_ST_fsm_state52 = 70'd2251799813685248;
parameter    ap_ST_fsm_state53 = 70'd4503599627370496;
parameter    ap_ST_fsm_state54 = 70'd9007199254740992;
parameter    ap_ST_fsm_state55 = 70'd18014398509481984;
parameter    ap_ST_fsm_state56 = 70'd36028797018963968;
parameter    ap_ST_fsm_state57 = 70'd72057594037927936;
parameter    ap_ST_fsm_state58 = 70'd144115188075855872;
parameter    ap_ST_fsm_state59 = 70'd288230376151711744;
parameter    ap_ST_fsm_state60 = 70'd576460752303423488;
parameter    ap_ST_fsm_state61 = 70'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 70'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 70'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 70'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 70'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 70'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 70'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 70'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 70'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 70'd590295810358705651712;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   rst;
input   btn1;
input   btn2;
input   btn3;
input   slow_clk;
output   lose;
output  [9:0] time_remaining_out_V;
input  [9:0] time_remaining_in_V;
input   verify1_out;
input   verify2_out;
input   verify3_out;

reg ap_idle;
reg lose;
reg[9:0] time_remaining_out_V;

(* fsm_encoding = "none" *) reg   [69:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] decrement_value;
reg   [0:0] newRound;
reg   [0:0] btn1_verify;
reg   [0:0] btn2_verify;
reg   [0:0] btn3_verify;
reg   [31:0] RandSeed;
wire   [0:0] slow_clk_read_read_fu_82_p2;
wire   [0:0] rst_read_read_fu_106_p2;
wire   [31:0] tmp_i_i_fu_180_p2;
reg   [31:0] tmp_i_i_reg_385;
wire    ap_CS_fsm_state3;
wire   [0:0] newRound_load_load_fu_172_p1;
wire    ap_CS_fsm_state4;
wire   [10:0] grp_fu_197_p2;
reg   [10:0] last_num_assign_1_reg_395;
wire    ap_CS_fsm_state39;
wire  signed [10:0] grp_fu_337_p3;
wire    ap_CS_fsm_state40;
wire  signed [10:0] grp_fu_222_p2;
reg  signed [10:0] last_num_assign_2_reg_405;
wire    ap_CS_fsm_state54;
wire  signed [10:0] grp_fu_346_p3;
wire    ap_CS_fsm_state55;
wire    ap_CS_fsm_state2;
wire   [31:0] tmp_1_fu_274_p2;
wire    ap_CS_fsm_state69;
wire   [0:0] not_or_cond3_i_fu_325_p2;
wire    ap_CS_fsm_state70;
wire   [0:0] tmp_3_i_fu_207_p2;
wire   [0:0] tmp_3_i6_fu_231_p2;
wire   [0:0] tmp_3_i1_fu_262_p2;
wire   [31:0] tmp_2_i_i_cast_fu_252_p1;
reg   [9:0] time_remaining_out_V_preg;
wire   [9:0] ssdm_int_V_write_ass_fu_166_p2;
reg    lose_preg;
wire   [9:0] tmp_2_fu_162_p1;
wire  signed [31:0] tmp_i_i_fu_180_p1;
wire   [31:0] grp_fu_197_p0;
wire   [7:0] grp_fu_197_p1;
wire   [6:0] tmp_4_fu_203_p1;
wire   [7:0] grp_fu_222_p1;
wire   [6:0] tmp_5_fu_227_p1;
wire   [7:0] grp_fu_243_p1;
wire   [10:0] grp_fu_243_p2;
wire   [6:0] tmp_6_fu_248_p1;
wire   [0:0] tmp_i1_fu_290_p1;
wire   [0:0] tmp1_i_fu_299_p1;
wire   [0:0] tmp2_i_fu_308_p1;
wire   [0:0] tmp1_i_fu_299_p2;
wire   [0:0] tmp2_i_fu_308_p2;
wire   [0:0] tmp_fu_313_p2;
wire   [0:0] tmp_i1_fu_290_p2;
wire   [0:0] or_cond3_i_fu_319_p2;
wire   [4:0] grp_fu_337_p0;
wire  signed [10:0] grp_fu_337_p1;
wire   [7:0] grp_fu_337_p2;
wire   [4:0] grp_fu_346_p0;
wire  signed [7:0] grp_fu_346_p1;
wire   [7:0] grp_fu_346_p2;
reg    grp_fu_197_ap_start;
wire    grp_fu_197_ap_done;
reg    grp_fu_222_ap_start;
wire    grp_fu_222_ap_done;
reg    grp_fu_243_ap_start;
wire    grp_fu_243_ap_done;
reg   [69:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 70'd1;
#0 decrement_value = 32'd1;
#0 newRound = 1'd0;
#0 btn1_verify = 1'd0;
#0 btn2_verify = 1'd0;
#0 btn3_verify = 1'd0;
#0 RandSeed = 32'd7;
#0 time_remaining_out_V_preg = 10'd0;
#0 lose_preg = 1'b0;
end

Game_logic_urem_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
Game_logic_urem_3bkb_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_197_ap_start),
    .done(grp_fu_197_ap_done),
    .din0(grp_fu_197_p0),
    .din1(grp_fu_197_p1),
    .ce(1'b1),
    .dout(grp_fu_197_p2)
);

Game_logic_urem_1cud #(
    .ID( 1 ),
    .NUM_STAGE( 15 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
Game_logic_urem_1cud_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_222_ap_start),
    .done(grp_fu_222_ap_done),
    .din0(grp_fu_337_p3),
    .din1(grp_fu_222_p1),
    .ce(1'b1),
    .dout(grp_fu_222_p2)
);

Game_logic_urem_1cud #(
    .ID( 1 ),
    .NUM_STAGE( 15 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
Game_logic_urem_1cud_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_243_ap_start),
    .done(grp_fu_243_ap_done),
    .din0(grp_fu_346_p3),
    .din1(grp_fu_243_p1),
    .ce(1'b1),
    .dout(grp_fu_243_p2)
);

Game_logic_mac_mudEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
Game_logic_mac_mudEe_U4(
    .din0(grp_fu_337_p0),
    .din1(grp_fu_337_p1),
    .din2(grp_fu_337_p2),
    .dout(grp_fu_337_p3)
);

Game_logic_mac_mueOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
Game_logic_mac_mueOg_U5(
    .din0(grp_fu_346_p0),
    .din1(grp_fu_346_p1),
    .din2(grp_fu_346_p2),
    .dout(grp_fu_346_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        time_remaining_out_V_preg <= 10'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (slow_clk_read_read_fu_82_p2 == 1'd1))) begin
            time_remaining_out_V_preg <= ssdm_int_V_write_ass_fu_166_p2;
        end else if (((1'b1 == ap_CS_fsm_state2) & (rst_read_read_fu_106_p2 == 1'd1))) begin
            time_remaining_out_V_preg <= 10'd640;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        btn1_verify <= tmp_3_i_fu_207_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (rst_read_read_fu_106_p2 == 1'd1))) begin
        btn1_verify <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state54)) begin
        btn2_verify <= tmp_3_i6_fu_231_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (rst_read_read_fu_106_p2 == 1'd1))) begin
        btn2_verify <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state69)) begin
        btn3_verify <= tmp_3_i1_fu_262_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (rst_read_read_fu_106_p2 == 1'd1))) begin
        btn3_verify <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state69)) begin
        decrement_value <= tmp_1_fu_274_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (rst_read_read_fu_106_p2 == 1'd1))) begin
        decrement_value <= 32'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state70)) begin
        newRound <= not_or_cond3_i_fu_325_p2;
    end else if (((1'b1 == ap_CS_fsm_state3) & (newRound_load_load_fu_172_p1 == 1'd1))) begin
        newRound <= 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (rst_read_read_fu_106_p2 == 1'd1))) begin
        newRound <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state69)) begin
        RandSeed[10 : 0] <= tmp_2_i_i_cast_fu_252_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        last_num_assign_1_reg_395 <= grp_fu_197_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state54)) begin
        last_num_assign_2_reg_405 <= grp_fu_222_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (newRound_load_load_fu_172_p1 == 1'd1))) begin
        tmp_i_i_reg_385 <= tmp_i_i_fu_180_p2;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_197_ap_start = 1'b1;
    end else begin
        grp_fu_197_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        grp_fu_222_ap_start = 1'b1;
    end else begin
        grp_fu_222_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        grp_fu_243_ap_start = 1'b1;
    end else begin
        grp_fu_243_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state70) | ((1'b1 == ap_CS_fsm_state2) & (rst_read_read_fu_106_p2 == 1'd1)))) begin
        lose = 1'd0;
    end else begin
        lose = lose_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (slow_clk_read_read_fu_82_p2 == 1'd1))) begin
        time_remaining_out_V = ssdm_int_V_write_ass_fu_166_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (rst_read_read_fu_106_p2 == 1'd1))) begin
        time_remaining_out_V = 10'd640;
    end else begin
        time_remaining_out_V = time_remaining_out_V_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (newRound_load_load_fu_172_p1 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state70;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state69 = ap_CS_fsm[32'd68];

assign ap_CS_fsm_state70 = ap_CS_fsm[32'd69];

assign ap_done = 1'b0;

assign ap_ready = 1'b0;

assign grp_fu_197_p0 = (32'd100 + tmp_i_i_reg_385);

assign grp_fu_197_p1 = 32'd100;

assign grp_fu_222_p1 = 11'd100;

assign grp_fu_243_p1 = 11'd100;

assign grp_fu_337_p0 = 11'd13;

assign grp_fu_337_p1 = last_num_assign_1_reg_395[10:0];

assign grp_fu_337_p2 = 11'd100;

assign grp_fu_346_p0 = 11'd13;

assign grp_fu_346_p1 = last_num_assign_2_reg_405;

assign grp_fu_346_p2 = 11'd100;

assign newRound_load_load_fu_172_p1 = newRound;

assign not_or_cond3_i_fu_325_p2 = (or_cond3_i_fu_319_p2 ^ 1'd1);

assign or_cond3_i_fu_319_p2 = (tmp_i1_fu_290_p2 | tmp_fu_313_p2);

assign rst_read_read_fu_106_p2 = rst;

assign slow_clk_read_read_fu_82_p2 = slow_clk;

assign ssdm_int_V_write_ass_fu_166_p2 = (time_remaining_in_V - tmp_2_fu_162_p1);

assign tmp1_i_fu_299_p1 = btn2;

assign tmp1_i_fu_299_p2 = (tmp1_i_fu_299_p1 ^ btn2_verify);

assign tmp2_i_fu_308_p1 = btn3;

assign tmp2_i_fu_308_p2 = (tmp2_i_fu_308_p1 ^ btn3_verify);

assign tmp_1_fu_274_p2 = (32'd2 + decrement_value);

assign tmp_2_fu_162_p1 = decrement_value[9:0];

assign tmp_2_i_i_cast_fu_252_p1 = grp_fu_243_p2;

assign tmp_3_i1_fu_262_p2 = ((tmp_6_fu_248_p1 > 7'd50) ? 1'b1 : 1'b0);

assign tmp_3_i6_fu_231_p2 = ((tmp_5_fu_227_p1 > 7'd50) ? 1'b1 : 1'b0);

assign tmp_3_i_fu_207_p2 = ((tmp_4_fu_203_p1 > 7'd50) ? 1'b1 : 1'b0);

assign tmp_4_fu_203_p1 = grp_fu_197_p2[6:0];

assign tmp_5_fu_227_p1 = grp_fu_222_p2[6:0];

assign tmp_6_fu_248_p1 = grp_fu_243_p2[6:0];

assign tmp_fu_313_p2 = (tmp2_i_fu_308_p2 | tmp1_i_fu_299_p2);

assign tmp_i1_fu_290_p1 = btn1;

assign tmp_i1_fu_290_p2 = (tmp_i1_fu_290_p1 ^ btn1_verify);

assign tmp_i_i_fu_180_p1 = RandSeed;

assign tmp_i_i_fu_180_p2 = ($signed({{1'b0}, {32'd13}}) * $signed(tmp_i_i_fu_180_p1));

always @ (posedge ap_clk) begin
    RandSeed[31:11] <= 21'b000000000000000000000;
    lose_preg <= 1'b0;
end

endmodule //Game_logic
